app/blueprints/posts/views.py
from flask import Blueprint, redirect, request, render_template, flash, url_for, current_app
from app.models import User, Post
from app import db
from app.forms import CreatePostForm, UpdatePostForm
from flask_login import login_required, current_user
from datetime import datetime

pb = Blueprint('posts', __name__, template_folder='templates')


@pb.route('/posts/', methods=['GET'])
def posts():
    query = request.args.get('q')
    
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if query:
        posts = Post.query.filter(Post.title.contains(query) | Post.body.contains(query))
    else:
        posts = Post.query.order_by(Post.timestamp.desc())
    posts_per_page = current_app.config['POSTS_PER_PAGE']
    pages = posts.paginate(page=page, per_page=posts_per_page)
    return render_template('posts/posts.html', posts=posts, pages=pages, query=query)


@pb.route('/posts/new/', methods=['GET', 'POST'])
@login_required
def new_post():
    form = CreatePostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data

        post = Post(title=title, body=body, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Nice post, but you can better', 'success')
        return redirect(url_for('posts.posts'))

    return render_template('posts/create_post.html', form=form)


@pb.route('/posts/<int:post_id>/', methods=['GET'])
def get_post(post_id):
    post = Post.query.get(post_id)
    return render_template('posts/post.html', post=post)


@pb.route('/posts/<int:post_id>/update/', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get(post_id)
    if current_user != post.author:
        flash('You don\'t have enough rights to update this post', 'warning')
        return redirect(url_for('posts.posts'))  
    form = UpdatePostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.timestamp = datetime.utcnow()
        db.session.commit()
        flash('I like it better now!', 'success')
        return redirect(url_for('posts.update_post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.body.data = post.body

    return render_template('posts/update_post.html', form=form, post=post)


@pb.route('/posts/<int:post_id>/delete/')
def delete_post(post_id):
    post = Post.query.get(post_id)
    
    if current_user != post.author:
        flash('You don\'t have enough rights to delete this post', 'warning')  
    else:
        title = post.title
        db.session.delete(post)
        db.session.commit()
        flash(f'Post {title} was deleted!', 'success')
    return redirect(url_for('posts.posts'))

app/blueprints/posts/templates/posts/create_post.html
{% extends "base.html" %}
{% from "_render_field.html" import render_field %}

{% block title %}Create New Post{% endblock %}
{% block content %}
    <br>
    <form method="POST" action="{{url_for('posts.new_post', next=request.args.get('next'))}}">
        {{ form.hidden_tag() }}
        <p class="h4">New Post</p>
        <hr>
        <div class="md-form form-group w-50">
            {{ render_field(form.title) }}
            {{ render_field(form.body) }}
            {{ form.submit(class_="btn btn-primary") }}
        </div>  
    </form>
{% endblock %}

app/blueprints/posts/templates/posts/post.html
{% extends "base.html" %}
{% block title%}{{post.title}}{% endblock %}

{% block content %}
<br>
<div class="content-section">
    <div class="media">
        <div class="media-body">
            <h3 class="account-heading">{{ post.author.username }}</h3>
            <p class="text-secondary">{{ post.timestamp }}</p>
        </div>
    </div>
</div>
<p class="h3">{{ post.title }}</p>
<p>{{ post.body }}</p>
{% endblock %}

app/blueprints/posts/templates/posts/posts.html
{% extends "base.html" %}

{% block title %}
    {% if title %}
    {{title}} - Blog
    {% else %}
    Blog
    {% endif %}
{% endblock %}

{% block content %}
    <br>
    <div class="container d-flex flex-column align-items-center">
    <form action="{{ url_for('posts.posts') }}" class="form-inline">
        <div class="form-group mx-sm-3 mb-2">
            <input type="text" class="form-control" name="q" value="{%if query%}{{query}}{% else %}Python{% endif %}">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Search</button>
    </form>
    </div>
    <br>
    <div class="container d-flex flex-column align-items-center">
    {% for post in pages.items %}
    <div class="card" style="width: 48rem;">
        <div class="card-body" >
          <h5 class="card-title text-right">{{post.author.username}}</h5>
          <h6 class="card-subtitle mb-2 text-muted text-right">{{post.timestamp}}</h6>
          <h5 class="card-title"><a href="{{ url_for('posts.get_post', post_id=post.id) }}">{{post.title}}</a></h5>
          <p class="card-text">{{post.body}}</p>
          <p class="card-text"><small class="text-muted">Last updated at {{post.timestamp}} </small></p>
          {% if current_user == post.author %}
                <button class="btn btn-outline-success"><a id="update-link" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</button></a>
                <button id="button-delete" data-toggle="modal" data-target="#delete-modal" class="btn btn-outline-danger float-right">Delete</button>
          {% endif %}
        </div>
    </div>
    <br>
    <!-- Modal -->
    <div class="container col d-flex justify-content-center">
    <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Do you really want to delete post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-danger"><a id="delete-link" href="{{url_for('posts.delete_post', post_id=post.id) }}">Delete</a></button>
            </div>
        </div>
        </div>
    </div>
    </div>
    
    {% endfor %}
    </div>
    <nav>
        <ul class="pagination justify-content-center">
            <li class="page-item {% if not pages.has_prev %} disabled {% endif %}">
                <a class="page-link" href="{{ url_for('posts.posts', page=pages.prev_num) }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a> 
            </li>
            {% for page in pages.iter_pages() %}
                <li class="page-item {% if page == pages.page %} active {% endif %}">
                    <a class="page-link" href="{{ url_for('posts.posts', page=page) }}">{{ page }}<span class="sr-only">(current)</span></a>   
                </li>
            {% endfor %}
            <li class="page-item {% if not pages.has_next %} disabled {% endif %}">
                <a class="page-link" href="{{ url_for('posts.posts', page=pages.next_num) }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a> 
            </li>
        </ul>
    </nav>
    <script type="text/javascript">
        $('#delete-modal').on('shown.bs.modal');
    </script>
    
{% endblock %}

app/blueprints/posts/templates/posts/update_post.html
{% extends 'base.html' %}
{% from "_render_field.html" import render_field %}
{% block title %}Update {{post.title}} {% endblock %}
{% block content %}
    <br>
    <form method="POST" action="{{url_for('posts.update_post', post_id=post.id)}}">
        {{ form.hidden_tag() }}
        <p class="h4">Update Post</p>
        <hr>
        <div class="md-form form-group w-50">
            {{ render_field(form.title) }}
            {{ render_field(form.body) }}
            {{ form.submit(class_="btn btn-primary") }}
        </div>  
    </form>
{% endblock %}