app/blueprints/main/views.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/')
@main.route('/index')
def show_main_page():
	return render_template('main/index.html')

@main.route('/bio')
def show_bio():
    return render_template('main/bio.html')

@main.route('/hobbies')
def show_hobbies():
    return render_template('main/hobbies.html')

app/blueprints/main/templates/main/bio.html
{% extends "base.html" %}
{% block title %}My Bio{% endblock %}
{% block content %}
    <p><a href="{{ url_for('main.show_main_page') }}">Back to main page</a></p>
    <h1>My biography</h1>
    <ol id="timeline">
        <p><li>2000 - I was born.</li></p>
        <p><li>2006 - I went to school.</li></p>
        <p><li>2014 - Changed school to PHTL.</li></p>
        <p><li>2017 - Entered the PNU.</li></p>
    </ol>
    
{% endblock %}

app/blueprints/main/templates/main/hobbies.html
{% extends "base.html" %}
{% block title %}My Bio{% endblock %}
{% block content %}
    <p><a href="{{ url_for('main.show_main_page') }}">Back to main page</a></p>
    <h1>List of my hobbies</h1>
    <ul>
        <div>
        <p><li>Music</li></p>
        <div><img class="img-border" id="music-img" src="{{ url_for('static', filename='images/meloman.jpg') }}"></div>
        </div>
        <div>
            <p><li>Programming</li></p>
            <div><img class="img-border" id="coding-img" src="{{ url_for('static', filename='images/programming.jpg') }}"></div>
        </div>
    </ul>
{% endblock %}

app/blueprints/main/templates/main/index.html
{% extends "base.html" %}
{% block title %}Roman Dorosh{% endblock %}
{% block content %}
    <div><h1>Welcome to my page!</h1></div>
    
    <div class="blocks"><img class="img-border" id="my_photo" src="{{ url_for('static', filename='/images/praha.jpg') }}"></div>
    <div class="blocks">
        <h3><b>20 y.o. software engeneering student from Ivano-Frankivsk<b></h3>
    </div>
    <div class="blocks">
        <div id="bio-link"><a href="{{ url_for('main.show_bio') }}">Bio</a></div>
        <div><a href="{{ url_for('main.show_hobbies') }}">Hobbies</a></div>
    </div>
{% endblock %}